config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: %i[create destroy]
  root to: 'posts#index'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :posts do
    collection do
      post :confirm
    end
    
  end

  resources :users do
    member do
      get :favs
    end
  end

  mount LetterOpenerWeb::Engine,at: "letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  mount_uploaders :image, ImageUploader
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, IconUploader
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  
  before_validation { email.downcase! }

  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites/1
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id) 
  end

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿をお気に入りに登録しました。"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿をお気に入り解除しました。"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  before_action :ensure_user, only: %i[ edit update destroy ]

  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
  end
  


  def new
    @post = Post.new
  end


  def edit
  end


  def create
    @post = current_user.posts.build(post_params)
    return render :new if params[:back]
    if @post.save
      PostCompleteMailer.post_complete(@post.user).deliver
      redirect_to posts_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    render :new if @post.invalid?
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '更新しました。'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: '投稿を削除しました。'
  end

  private
  
  def ensure_user
    @posts = current_user.posts
    @post = @posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :user_id, {image: []}, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only:[:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'ログインしました'
      redirect_to  root_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only:[:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    return redirect_to root_path unless current_user.id == @user.id
  end

  def favs
    @user = User.find(params[:id])
    favs = Favorite.where(user_id: @user.id).pluck(:post_id)
    @fav_posts = Post.find(favs)
  end

  # GET /users/new
  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)  
    if @user.save
      redirect_to user_path(@user.id), notice: "User was successfully created." 
    else
      redirect_to new_user_path, status: :unprocessable_entity
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "User was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirm, :icon)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Copygram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b893fb5e5f.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <div id="wrap">
      <header>
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-dark shadow fixed-top">
            <a class="navbar-brand mb-0 h1" href="/"><img src='/images/bd_name.png' width="68" height=auto></a>
            <% if logged_in? %>
              <%= link_to '+New Post', new_post_path, class:"btn btn-outline-light" %>
            <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto ">
                <% if logged_in? %>
                  <li class="nav-item active", data-toggle="tooltip", title="プロフィールを確認">
                    <%= link_to user_path(current_user.id), class: "nav-link" do %><i class="fa-solid fa-user"> <%= @current_user.name %> でログイン中</i><% end %>
                  </li>
                  <li class="nav-item active", data-toggle="tooltip", title="お気に入り一覧">
                    <%= link_to favs_user_path(current_user.id),  class:"nav-link" do %><i class="fa-solid fa-heart text-white"><span class="d-lg-none"> お気に入り一覧</span></i><% end %>
                  </li>
                  <li class="nav-item active" , data-toggle="tooltip", title="ログアウト">
                    <%= link_to session_path(current_user.id), method: :delete, class: "nav-link" do %><i class="fa-solid fa-right-from-bracket"><span class="d-lg-none"> ログアウト</span></i><% end %>
                  </li>
                  <li class="nav-item active", data-toggle="tooltip", title="ホーム">
                    <%= link_to posts_path, class: "nav-link" do %><i class="fa-solid fa-house"><span class="d-lg-none"> ホーム</span></i><% end %>
                  </li>
                <% else %>
                  <li class="nav-item active">
                    <%= link_to new_user_path, class: "nav-link" do %><i class="fa-solid fa-user-plus"> アカウントを新規作成 </i><% end %>
                  </li>
                  <li class="nav-item active">
                    <%= link_to new_session_path, class: "nav-link" do %><i class="fa-solid fa-right-to-bracket"> ログイン </i><% end %>
                  </li>
                <% end %>

              </ul>
            </div>
          </nav>
        </div>
      </header>

      <div class="container mt-5 pt-5">
        <div class="row p-2 mr-2 justify-content-end fixed-bottom text-right">
            <% flash.each do |key, value| %>
              <%= content_tag(:div, value, class: "#{key}") %>
            <% end %>
        </div>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="row  p-4 justify-content-center">
  <%= form_with(model: @post, local:true, url: choose_new_or_edit ) do |form| %>

    <div class="form-group row">
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>
          <ul>
            <% @post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  
    <div class="form-group row">
      <%= form.label :content, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_area :content, rows:"7", class:"form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :image, class:"col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.file_field :image, required:true, multiple: true, accept: 'image/jpg,image/jpeg,image/png,image/gif', class:"form-control" %>
        <p class="text-muted fw-light">画像を複数枚同時に投稿することができます。</p>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class:"btn btn-primary mt-2" %>
    </div>
    
  <% end %>
</div>

app/views/posts/confirm.html.erb
<div class="row h4 pd-1 justify-content-center text-muted">投稿確認</div>

  <%= form_with(model: @post, local:true) do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image %>
    <%= form.hidden_field :image_cache %>
    <div class="row justify-content-center mb-5">
      <div class="post_block">
        <div class="block_text">
          <div class="post_header d-flex align-items-center">
            <div class="name">
              <% if @post.user.icon? %>
                <%= image_tag @post.user.icon.url, class:"icon_image" %>
              <% else %>
                <%= image_tag 'user_default_icon.png', class:"icon_image" %>
              <% end %>
              <%= @post.user.name.truncate(14) %>
            </div>
          </div>
        
          <div class="image_area bg-secondary">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="6000">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <% @post.image.drop(1).count.times do |index| %>
                  <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
                <% end %>
              </ol>
            
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <% @post.image.first(1).each do |image| %>
                    <%= image_tag image.to_s,  class: "carousel_image"  %>
                  <% end %>
                </div> 
                <% @post.image.drop(1).each do |image| %>
                  <div class="carousel-item">
                    <%= image_tag image.to_s, class: "carousel_image" %>
                  </div>
                <% end %>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        
          <div class="text_area">
            <div class="contents"><%= @post.content %></div>
            <div class="date">YY-MM-DD hh:mm (Posting date)</div>
          </div>
        </div>
      </div>
    </div>

    <div class="row pt-1 pb-1 justify-content-center text-muted">
      この内容で投稿してもよろしいですか？
    </div>

    <div class="row  pb-3 justify-content-center">
      <div class="md-4">
        <%= form.submit "投稿する", class:"btn btn-primary mt-2" %>
        <%= form.submit "もどる", name: 'back',  class:"btn btn-secondary mt-2" %>
      </div>
  
  <% end %>
</div>

  

app/views/posts/edit.html.erb
<div class="container bg-light rounded">
  <%= render 'form', post: @post %>
  <%= link_to '⇦編集を破棄して戻る', posts_path, class:"text-muted" %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <% @favorite = current_user.favorites.find_by(post_id: post.id)  %>
  <div class="row justify-content-center mb-5">
    <div class="post_block">
      <div class="block_text">
        <div class="post_header d-flex align-items-center">
          <div class="name">
            <% if post.user.icon? %>
              <%= image_tag post.user.icon.url, class:"icon_image" %>
            <% else %>
              <%= image_tag 'user_default_icon.png', class:"icon_image" %>
            <% end %>
            <%= post.user.name.truncate(14) %>
          </div>
          
          <% if current_user.id == post.user_id %>
            <div class="menu_icon">
              <div class="modal-open" data-target="#modal-<%= post.id.to_s %>" data-toggle="tooltip" title="投稿者用メニュー">
                <i class="fa-solid fa-plus fa-lg text-muted"></i>
              </div>
            </div>                
            
            <div class="modal-container" id="modal-<%= post.id.to_s %>">
              <div class="modal-body">                   
                <div class="modal-close" data-target="#modal-<%= post.id.to_s %>">×</div>                  
                <div class="modal-content">
                  <ul class="list-group text-center">
                    <li class="list-group-item"><%= link_to "詳細を確認する", post_path(post.id), class:"text-secondary"  %></li>
                    <li class="list-group-item"><%= link_to "投稿を編集する", edit_post_path(post.id), class:"text-secondary"  %></li>
                    <li class="list-group-item"><%= link_to "投稿を削除する", post_path(post.id), method: :delete, class:"text-danger", data: { confirm: '投稿を削除してよろしいですか？'}  %></li>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="image_area bg-secondary">
          
          <div id="post<%= post.id.to_s %>" class="carousel slide" data-ride="carousel" data-interval="6000">
            <ol class="carousel-indicators">
              <li data-target= "#post<%= post.id.to_s %>" data-slide-to="0" class="active"></li>
              <% post.image.drop(1).count.times do |index| %>
                <li data-target="#post<%= post.id.to_s %>"  data-slide-to="#{index}"></li>
              <% end %>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <% post.image.first(1).each do |image| %>
                  <%= image_tag image.to_s, class: "carousel_image"  %>
                <% end %>
              </div> 
              <% post.image.drop(1).each do |image| %>
                <div class="carousel-item">
                  <%= image_tag image.to_s, class: "carousel_image" %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#post<%= post.id.to_s %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post<%= post.id.to_s %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          
        </div>
        <div class="text_area">
          <% if logged_in? %>
            <div class="icons">
              <% unless @favorite.present? %>
                <div data-toggle="tooltip", title="Favorite!">
                  <%= link_to favorites_path(post_id: post.id), method: :post do %>
                    <i class="fa-regular fa-heart fa-2x text-muted"></i>
                  <% end %>
                </div>
              <% else %>
                <div data-toggle="tooltip", title="UnFavorite!">
                  <%= link_to favorite_path(id: @favorite.id), method: :delete do %>
                    <i class="fa-solid fa-heart fa-2x text-danger"></i>
                  <% end %>
                </div>
              <% end %>  
            </div>
          <% end %>
          <div class="contents">
            <%= post.content.truncate(28) %>
            <%= link_to post_path(post.id) do %> <p class="text-muted">+詳細を確認する</p> <% end %>
          </div>
          <div class="date"><%= post.created_at.strftime("%y-%m-%d %H:%M") %> Posted</div>                        
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container bg-light rounded">
  <%= render 'form', post: @post %>
  <%= link_to '⇦編集を破棄して戻る', posts_path, class:"text-muted" %>
</div>

app/views/posts/show.html.erb
<div class="row justify-content-center mb-5">
  <div class="post_block">
    <div class="block_text">
      <div class="post_header d-flex align-items-center">
        <div class="name">
          <% if @post.user.icon? %>
            <%= image_tag @post.user.icon.url, class:"icon_image" %>
          <% else %>
            <%= image_tag 'user_default_icon.png', class:"icon_image" %>
          <% end %>
          <%= @post.user.name.truncate(14) %>
        </div>        
        <% if current_user.id == @post.user_id %>
          <div class="menu_icon">
            <div class="modal-open" data-target="#modal-<%= @post.id.to_s %>"  data-toggle="tooltip" title="投稿者用メニュー">
              <i class="fa-solid fa-plus fa-lg text-muted"></i>
            </div>
          </div>
          <div class="modal-container"  id="modal-<%= @post.id.to_s %>">
            <div class="modal-body">
              <div class="modal-close" data-target="#modal-<%= @post.id.to_s %>">×</div>
              <div class="modal-content">
                <ul class="list-group text-center">
                  <li class="list-group-item"><%= link_to "投稿を編集する", edit_post_path(@post.id), class:"text-secondary"  %></li>
                  <li class="list-group-item"><%= link_to "投稿を削除する", post_path(@post.id), method: :delete, class:"text-danger", data: { confirm: '投稿を削除してよろしいですか？'}  %></li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="image_area bg-secondary">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="3000">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <% @post.image.drop(1).count.times do |index| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% @post.image.first(1).each do |image| %>
                <%= image_tag image.to_s, class: "carousel_image"  %>
              <% end %>
            </div> 
            <% @post.image.drop(1).each do |image| %>
              <div class="carousel-item">
                <%= image_tag image.to_s, class: "carousel_image" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="text_area">
        <div class="contents">
          <%= @post.content %>
        </div>
        <div class="date"><%= @post.created_at.strftime("%y-%m-%d %H:%M") %> Posted</div>        
      </div>
    </div>
  </div>
</div>

<div class="row  pb-3 justify-content-center">
  <div class="md-4">
    <%= link_to 'top', posts_path,  class:"btn btn-secondary md-4" %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row  p-4 justify-content-center">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      
        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    
    <div class="row mb-2 justify-content-center">
      <strong>ユーザーアイコン:</strong>
    </div>
    
  
    <div class="row mb-3 justify-content-center">  
      <% if @user.icon? %>
        <%= image_tag @user.icon.url, class:"icon_image" %>
      <% else %>
        <%= image_tag 'user_default_icon.png', class:"icon_image" %>
      <% end %>
    </div>
  
    <div class="form-group row">
      <%= form.label :name, class:"col-sm-6 col-form-label" do%>ユーザーネーム<% end %>
      <div class="col-sm-10">
        <%= form.text_field :name, class:"form-control" %>
      </div>
    </div>
  
    <div class="form-group row">
      <%= form.label :icon, class:"col-sm-6 col-form-label" do%>アイコン画像<% end %>
      <div class="col-sm-10">
        <%= form.file_field :icon, class:"form-control" %>
      </div>
    </div>
  
    <div class="form-group row">
      <%= form.label :email, class:"col-sm-6 col-form-label" do%>メールアドレス<% end %>
      <div class="col-sm-10">
        <%= form.text_field :email, class:"form-control" %>
      </div>
    </div>
  
    <div class="form-group row">
      <%= form.label :password, class:"col-sm-6 col-form-label" do%>パスワード<% end %>
      <div class="col-sm-10">
        <%= form.text_field :password, class:"form-control" %>
      </div>
    </div>
  
    <div class="form-group row">
      <%= form.label :password_confirmation, class:"col-sm-6 col-form-label" do %>パスワード(確認)<% end %>
      <div class="col-sm-10">
        <%= form.text_field :password_confirmation, class:"form-control" %>
      </div>
    </div>
  
    <div class="actions">
      <%= form.submit class:"btn btn-primary mt-4" %>
    </div>
  
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row h4 pd-1 justify-content-center text-muted">アカウント情報を編集する</div>
<div class="container bg-light rounded">
  <%= render 'form', user: @user %>
  <%= link_to '⇦編集を破棄して戻る', user_path(@user.id), class:"text-muted" %>
</div>

app/views/users/favs.html.erb
<div class="row h4 pb-1 justify-content-center text-muted">あなたがお気に入りした投稿</div>
<% @fav_posts.each do |post| %>
  <% @favorite = current_user.favorites.find_by(post_id: post.id)  %>
  <div class="row justify-content-center mb-5">
    <div class="post_block">
      <div class="block_text">
      <div class="post_header d-flex align-items-center">
        <div class="name">
          <% if post.user.icon? %>
            <%= image_tag post.user.icon.url, class:"icon_image" %>
          <% else %>
            <%= image_tag 'user_default_icon.png', class:"icon_image" %>
          <% end %>
          <%= post.user.name.truncate(14) %>
        </div>
        <% if current_user.id == post.user_id %>
        <div class="menu_icon">
          <div class="modal-open" data-target="#modal-<%= post.id.to_s %>" data-toggle="tooltip" title="投稿者用メニュー">
            <i class="fa-solid fa-plus fa-lg text-muted"></i>
          </div>
        </div>        
        <div class="modal-container" id="modal-<%= post.id.to_s %>">
          <div class="modal-body">            
            <div class="modal-close" data-target="#modal-<%= post.id.to_s %>">×</div>            
            <div class="modal-content">
              <ul class="list-group text-center">
                <li class="list-group-item"><%= link_to "詳細を確認する", post_path(post.id), class:"text-secondary"  %></li>
                <li class="list-group-item"><%= link_to "投稿を編集する", edit_post_path(post.id), class:"text-secondary"  %></li>
                <li class="list-group-item"><%= link_to "投稿を削除する", post_path(post.id), method: :delete, class:"text-danger", data: { confirm: '投稿を削除してよろしいですか？'}  %></li>
              </ul>
            </div>
          </div>
        </div>
        <% end %>        
      </div>
      <div class="image_area bg-secondary">
        <div id="post<%= post.id.to_s %>" class="carousel slide" data-ride="carousel" data-interval="6000">
          <ol class="carousel-indicators">
            <li data-target= "#post<%= post.id.to_s %>" data-slide-to="0" class="active"></li>
            <% post.image.drop(1).count.times do |index| %>
              <li data-target="#post<%= post.id.to_s %>"  data-slide-to="#{index}"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% post.image.first(1).each do |image| %>
                <%= image_tag image.to_s, class: "carousel_image"  %>
              <% end %>
            </div> 
            <% post.image.drop(1).each do |image| %>
              <div class="carousel-item">
                <%= image_tag image.to_s, class: "carousel_image" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#post<%= post.id.to_s %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#post<%= post.id.to_s %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="text_area">
        <% if logged_in? %>
          <div class="icons">
            <% unless @favorite.present? %>
              <div data-toggle="tooltip", title="Favorite!">
                <%= link_to favorites_path(post_id: post.id), method: :post do %>
                  <i class="fa-regular fa-heart fa-2x text-muted"></i>
                <% end %>
              </div>
            <% else %>
              <div data-toggle="tooltip", title="UnFavorite!">
                <%= link_to favorite_path(id: @favorite.id), method: :delete do %>
                  <i class="fa-solid fa-heart fa-2x text-danger"></i>
                <% end %>
              </div>
            <% end %>  
          </div>
        <% end %>
        <div class="contents">
          <%= post.content.truncate(28) %>
          <%= link_to post_path(post.id) do %> <p class="text-muted">+詳細を確認する</p> <% end %>
        </div>
        <div class="date"><%= post.created_at.strftime("%y-%m-%d %H:%M") %> Posted</div>        
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row h4 pd-1 justify-content-center text-muted">新規アカウント作成</div>
<div class="container bg-light rounded">
  <%= render 'form', user: @user %>
  <%= link_to '⇦ログインフォームへ', new_session_path, class:"text-muted" %>
</div>

app/views/users/show.html.erb
<div class="container bg-light rounded">
  <div class="row  mb-4 justify-content-center">
    <strong>Name:</strong>
    <%= @user.name %>
  </div>
  
  <div class="row  mb-2 justify-content-center">
    <strong>Icon:</strong>
  </div>

  <div class="row  mb-4 justify-content-center">
    <% if @user.icon? %>
      <%= image_tag @user.icon.url, class:"icon_image" %>
    <% else %>
      <%= image_tag 'user_default_icon.png', class:"icon_image" %>
    <% end %>
  </div>
  
  <div class="row  mb-4 justify-content-center">
    <strong>Email:</strong>
    <%= @user.email %>
  </div>
  
  <div class="row  pb-3 justify-content-center">
    <div class="md-4">
      <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary md-4" %> 
      <%= link_to 'Back', posts_path,  class:"btn btn-secondary md-4" %>
    </div>
  </div>

</div>